[doc("Default command; list all available commands.")]
@list:
  just --list --unsorted

[doc("Install example app dependencies.")]
install:
  pnpm install --ignore-workspace

[doc("Run the example app on Android.")]
run-android:
  pnpm run android
