[doc("Default command; list all available commands.")]
@list:
  just --list --unsorted

[group("Test")]
[doc("Remove all build artifacts and installed dependencies.")]
clean:
  rm -rf node_modules
  rm -rf .expo/
  rm -rf ios/build/
  rm -rf ios/Pods/
  rm -rf android/.gradle/
  rm -rf android/build/
  rm -rf android/app/build/
  rm -rf android/app/.cxx/

[doc("Install example app dependencies.")]
install:
  pnpm install --ignore-workspace

[doc("Run the example app on Android.")]
run-android:
  pnpm run android

[doc("Install iOS CocoaPods dependencies.")]
pod-install:
  cd ios && pod install

[doc("Run the example app on an iOS simulator.")]
run-ios:
  pnpm run ios
