[group("Repo")]
[doc("Default command; list all available commands.")]
@list:
  just --list --unsorted

[group("Test")]
[doc("Remove all build artifacts and installed dependencies.")]
clean:
  rm -rf node_modules/
  rm -rf android/build/

[group("Test")]
[doc("Run the tests on the Android application (needs a running emulator).")]
test:
  rm -rf node_modules/bdk-rn
  pnpm install --ignore-workspace
  pnpm run android
