name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: pnpm lint

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install just
        run: sudo apt-get update && sudo apt-get install -y just

      - name: Apply bdk-ffi patches
        run: just submodule-apply-patch

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@1fbea72663f6d4c03efaab13560c8a24cfd2a7cc # v1.9.0
        with:
          toolchain: 1.91.1
          target: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

      - name: Cache Rust build
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          workspaces: bdk-ffi/bdk-ffi

      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Build Android binaries and generate bindings
        run: pnpm ubrn:android --config ubrn.config.yaml

      - name: Typecheck files
        run: pnpm typecheck

      - name: Build package
        run: pnpm prepare

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install just
        run: brew install just

      - name: Apply bdk-ffi patches
        run: just submodule-apply-patch

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@1fbea72663f6d4c03efaab13560c8a24cfd2a7cc # v1.9.0
        with:
          toolchain: 1.91.1
          target: aarch64-apple-ios,aarch64-apple-ios-sim,x86_64-apple-ios

      - name: Cache Rust build
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          workspaces: bdk-ffi/bdk-ffi

      - name: Build iOS binaries and generate bindings
        run: pnpm ubrn:ios --config ubrn.config.yaml
